encode:
  emit_byteorder_mark: false
  input_encoding: "utf-8"
  output_encoding: "utf-8"
format:
  always_wrap: []
  autosort: true
  command_case: "canonical"
  dangle_align: "prefix"
  dangle_parens: true
  disable: false
  enable_sort: true
  fractional_tab_policy: "use-space"
  keyword_case: "canonical"
  layout_passes: {}
  line_ending: "unix"
  line_width: 80
  max_lines_hwrap: 999
  max_pargs_hwrap: 2
  max_prefix_chars: 4
  max_rows_cmdline: 2
  max_subgroups_hwrap: 2
  min_prefix_chars: 4
  require_valid_layout: true
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  tab_size: 4
  use_tabchars: false
lint:
  argument_var_pattern: "[a-z][a-z0-9_]+"
  disabled_codes: []
  function_pattern: "[0-9a-z_]+"
  global_var_pattern: "[A-Z][0-9A-Z_]+"
  internal_var_pattern: _[A-Z][0-9A-Z_]+
  keyword_pattern: "[A-Z][0-9A-Z_]+"
  local_var_pattern: "[a-z][a-z0-9_]+"
  macro_pattern: "[0-9A-Z_]+"
  max_arguments: 5
  max_branches: 12
  max_conditionals_custom_parser: 2
  max_localvars: 15
  max_returns: 6
  max_statement_spacing: 2
  max_statements: 50
  min_statement_spacing: 1
  private_var_pattern: _[0-9a-z_]+
  public_var_pattern: "[A-Z][0-9A-Z_]+"
markup:
  bullet_char: "*"
  canonicalize_hashrulers: true
  enable_markup: true
  enum_char: .
  explicit_trailing_pattern: "#<"
  fence_pattern: ^\s*([`~]{3}[`~]*)(.*)$
  first_comment_is_literal: false
  hashruler_min_length: 10
  literal_comment_pattern: null
  ruler_pattern: ^\s*[^\w\s]{3}.*[^\w\s]{3}$
misc:
  per_command: {}
parse:
  additional_commands: {}
  override_spec: {}
  proptags: []
  vartags: []
