jobs:
  build:
    permissions:
      contents: "read"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"
      - name: "Build"
        uses: "./.github/actions/build"
        with:
          package: "${{ matrix.package }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
    strategy:
      fail-fast: false
      matrix:
        package:
          - "serilib"
          - "serilib-arm-m0plus"
          - "serilib-arm-m3"
          - "serilib-arm-m4"
          - "serilib-armhf-m33"
          - "serilib-armhf-m4"
          - "serilib-armhf-m55"
          - "serilib-armhf-m55-double"
          - "serilib-armhf-m7"
          - "serilib-armhf-m7-double"
          - "serilib-armhf-m85"
          - "serilib-armhf-m85-double"
          - "serilib-riscv32-esp32c3"
          - "serilib-shared"
name: "CMake Build"
on:
  pull_request:
  push:
  workflow_dispatch:
